name: ServerFreeze
author: Glenjendary
main: com.glenjendary.freeze.main
description: Allows you to freeze all the players on your server incase something goes wrong.
commands:
  sfreeze:
    usage: /sfreeze
    description: Freezes the server.
    aliases: [sf, serverf, serverfreeze]
